{% set version = "0.7.0.post2" %}

package:
  name: python-symengine
  version: {{ version }}

source:
  url: https://github.com/symengine/symengine.py/archive/v{{ version }}.tar.gz
  sha256: 1b645c6a53a67f692a8222f1765f9fe00de5df065b84b5e0458395d4a7f700b0

build:
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make   # [unix]
    - ninja  # [win]
  host:
    - symengine     {{ ".".join(version.split(".")[:2]) }}
    - gmp           # [unix]
    - mpir          # [win]
    - mpfr
    - mpc
    - libflint
    - python
    - cython
    - setuptools
  run:
    - {{ pin_compatible("symengine", max_pin="x.x") }}
    - python
    - gmp           # [unix]
    - mpir          # [win]
    - mpfr
    - mpc
    - libflint

test:
  requires:
    - pytest
    - sympy
  imports:
    - symengine

about:
  home: https://github.com/symengine/symengine.py
  license: MIT
  license_file: LICENSE
  summary: Python wrappers for SymEngine, a fast symbolic manipulation library, written in C++

extra:
  recipe-maintainers:
    - isuruf
    - certik
