{% set version = "0.10.0" %}

package:
  name: python-symengine
  version: {{ version }}

source:
  url: https://github.com/symengine/symengine.py/archive/v{{ version }}.tar.gz
  sha256: 923944ab54aa0a787629424c101f5ec6a87b44177c669d21c7d3b0257f725927

build:
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - pip                                    # [build_platform != target_platform]
    - setuptools <60                         # [build_platform != target_platform]
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make   # [unix]
    - ninja  # [win]
  host:
    - symengine     {{ ".".join(version.split(".")[:2]) }}
    - gmp           # [unix]
    - mpir          # [win]
    - mpfr
    - mpc
    - libflint
    - python
    - cython
    - setuptools <60
    - pip
  run:
    - {{ pin_compatible("symengine", max_pin="x.x") }}
    - python
    - gmp           # [unix]
    - mpir          # [win]
    - mpfr
    - mpc
    - libflint

test:
  requires:
    - pytest
    - sympy
  imports:
    - symengine

about:
  home: https://github.com/symengine/symengine.py
  license: MIT
  license_file: LICENSE
  summary: Python wrappers for SymEngine, a fast symbolic manipulation library, written in C++

extra:
  recipe-maintainers:
    - isuruf
    - certik
