{% set version = "0.4.0" %}

package:
  name: python-symengine
  version: {{ version }}

source:
  url: https://github.com/symengine/symengine.py/archive/v{{ version }}.tar.gz
  sha256: b9e9884649a3563e24d4b90143e50c9a3ccd6518ea4bf7d7ed819aafc2ce24a2

build:
  number: 0
  skip: true        # [win and not py>=35]

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - symengine     0.3.0
    - gmp           # [unix]
    - mpir          # [win]
    - mpfr
    - mpc
    - libflint         # [unix]
    - python
    - cython
    - setuptools
  run:
    - symengine     0.3.0
    - python
    - gmp           # [unix]
    - mpir          # [win]
    - mpfr
    - mpc
    - libflint         # [unix]

test:
  requires:
    - pytest
    - sympy
  imports:
    - symengine

about:
  home: https://github.com/symengine/symengine.py
  license: MIT
  license_file: LICENSE
  summary: 'Python wrappers for SymEngine, a fast symbolic manipulation library, written in C++'

extra:
  recipe-maintainers:
    - isuruf
    - certik
