{% set version = "0.14.0" %}

package:
  name: python-symengine
  version: {{ version }}

source:
  url: https://github.com/symengine/symengine.py/archive/v{{ version }}.tar.gz
  sha256: 38e742a9b3d03b36f07b2ccba39e7e3d626e37557c26bb03ce575b95cfbd9cc4

build:
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - pip                                    # [build_platform != target_platform]
    - cmake
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - make   # [unix]
    - ninja  # [win]
  host:
    - symengine     {{ ".".join(version.split(".")[:2]) }}
    - gmp
    - mpfr
    - mpc
    - libflint
    # - winpthreads-devel  # [win]
    - python
    - cython
    - pip
    - setuptools
  run:
    - python

test:
  requires:
    - pytest
    - sympy
  imports:
    - symengine

about:
  home: https://github.com/symengine/symengine.py
  license: MIT
  license_file: LICENSE
  summary: Python wrappers for SymEngine, a fast symbolic manipulation library, written in C++

extra:
  recipe-maintainers:
    - isuruf
    - certik
